apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-guided-goshawk
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "957204945901"
    provider: eks
    region: ap-southeast-2
    registry: 957204945901.dkr.ecr.ap-southeast-2.amazonaws.com
  environments:
  - key: dev
    owner: cub-d
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: 52.62.98.222.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jx-bot-2021
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-guided-goshawk-20210818010848421600000004
  - name: reports
    url: s3://reports-tf-jx-guided-goshawk-20210818010848430200000007
  - name: repository
    url: s3://repository-tf-jx-guided-goshawk-20210818010848421500000003
  terraform: true
  vault:
    aws:
      dynamoDBRegion: ap-southeast-2
      dynamoDBTable: vault-unseal-tf-jx-guided-goshawk-jAI6wf48
      kmsKeyId: 39d4082-6025-464a-80fa-bbe32381c6df
      kmsRegion: ap-southeast-2
      s3Bucket: vault-unseal-tf-jx-guided-goshawk-20210818010848427800000008
      s3Region: ap-southeast-2
  webhook: lighthouse
