apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        briancole01/demo1: true
        briancole01/demo2: true
        briancole01/demo3: true
        briancole01/demo5: true
        briancole01/demo6: true
        cub-d/jx3-eks-vault: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        briancole01/demo1: merge
        briancole01/demo2: merge
        briancole01/demo3: merge
        briancole01/demo5: merge
        briancole01/demo6: merge
        cub-d/jx3-eks-vault: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cub-d/jx3-eks-vault
        - briancole01/demo1
        - briancole01/demo2
        - briancole01/demo3
        - briancole01/demo5
        - briancole01/demo6
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - cub-d/jx3-eks-vault
        - briancole01/demo1
        - briancole01/demo2
        - briancole01/demo3
        - briancole01/demo5
        - briancole01/demo6
      target_url: http://lighthouse-jx.52.62.98.222.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
