apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: briancole01
    provider: https://github.com
    providerKind: github
    repositories:
    - name: demo1
    - name: demo2
    - name: demo3
    - name: demo5
    - name: demo6
    scheduler: in-repo
  - owner: cub-d
    provider: https://github.com
    providerKind: github
    repositories:
    - name: demo-6
    - name: demo7
    - name: demo8
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
